### ISSUE TITLE
Too strict instrument frequency validation?

### ISSUE THREAD

**Issue by mvtiaine** [grzegorz-kraszewski/libdigibooster3#6]
https://github.com/grzegorz-kraszewski/libdigibooster3/blob/master/loader.c#L196

A few mods in AMP/Modland fail due to this check:
`if ((mis->C3Freq < 2000) || (mis->C3Freq > 192000)) return 0;`

Changing the check to:
`if ((mis->C3Freq < 1000) || (mis->C3Freq > 192000)) return 0;`

fixes for example:
https://amp.dascene.net/downmod.php?index=89660
https://amp.dascene.net/downmod.php?index=38856

**Comment by grzegorz-kraszewski** [comment]
There are some assumptions made in libdigibooster3 player engine, DigiBooster 3 application and other places about minimum sampling rate of an instrument. Modifying the check here will have consequences. I'm against it.

**Comment by mvtiaine** [comment]
Ok, thanks for the info.

**Comment by grzegorz-kraszewski** [comment]
The only safe solution would be to upsample the instrument when loading (by factor of two for example, to make upsampler lowpass filter fixed). However it may create additional problems if commands 9xx (sample offset) E7x (coarse sample offset) or Oxx (sample offset slide) are used on the instrument.
